### ISSUE TITLE
Command about init submodules

### ISSUE THREAD

**Issue by QiFuChina** [SamsungLabs/rome#1]
Hi,
I follow the instructure but the first step ```git init --recursive submodules``` shows ```error: unknown option `recursive' ``` . I remove gitmodules ```.git``` and try it again it shows same error.
Then I search other information and try ```git submodule update --init --recursive```, it happens nothing like that
![微信截图_20220726103614](https://user-images.githubusercontent.com/24989456/180910861-55740446-8c47-48b9-b1e9-c3ba040a6cac.png)
![微信截图_20220726103626](https://user-images.githubusercontent.com/24989456/180910936-2dc8e565-2779-48b9-857d-9231970a849e.png)
Did I miss something?
Thanks

**Comment by khakhulin** [comment]
Thanks for pointing this out! I skipped to push initialization. Fixed it. Also, the proper command would be: `git submodule update --init --recursive `

**Comment by QiFuChina** [comment]
> Thanks for pointing this out! I skipped to push initialization. Fixed it. Also, the proper command would be: `git submodule update --init --recursive `

Thanks for replying, when I install requirements.txt  it shows ```
ERROR: Could not find a version that satisfies the requirement apex==0.1 (from versions: 0.9.8dev.linux-i686, 0.9.8.dev0, 0.9.8a0.dev0, 0.9.9.dev0, 0.9.10.dev0)
ERROR: No matching distribution found for apex==0.1
```
I'm  using windows platform so do I change it to linux to execute this?

**Comment by khakhulin** [comment]
I see, the requirements is redundant in current state. I will remove apex, but for simplicity try to run in colab or install locally torch, pytorch3d, face-alignment (I'm not sure it works on windows).
