### ISSUE TITLE
About the training dataset

### ISSUE THREAD

**Issue by xmlyqing00** [SamsungLabs/rome#19]
Hi,

Nice work! I'm interested in reimplementing the training process. 
1. Since you use the VoxCeleb2 dataset, do you have any suggestions on downloading the dataset? I found that the official website doesn't support batch-downloading videos. 
2. Do you use VoxCeleb1 or VoxCeleb2 dataset?

Thanks!

**Comment by khakhulin** [comment]
Hi! 
We use VoxCeleb2 and we filter dataset with respect to image quality since most head segmentation networks cannot work on noisy images
I suggest using the recently proposed https://celebv-hq.github.io/ for the best quality.

**Comment by xmlyqing00** [comment]
Thank you! I'll check this dataset. It's really annoying that many youtube videos are missing. 

I have the following question when you used DECA to reconstruct the face model, why you not use the detailed map (detail displacement map) from DECA? It should provide more geometry details, right? 

Thanks for your time.

**Comment by xmlyqing00** [comment]
I see. Thank you for your comments.
