### ISSUE TITLE
questions about infer.py

### ISSUE THREAD

**Issue by ZekuiQin** [SamsungLabs/rome#2]
Thanks for authors' great work.
I have some questions about infer.py:

(1)Can not find **args.align_source** and **args.align_scale** in infer.py.
(2)I got strange results when setting args.align_source as False (the source and the drive images are data/imgs/taras1.jpg):
![iTerm2 6TbboX render_result](https://user-images.githubusercontent.com/40821171/181002240-60d87601-537b-47fe-9296-d64fc1ed2709.png)
![iTerm2 Pry6d0 shape_result](https://user-images.githubusercontent.com/40821171/181002268-a128a598-85eb-4988-aae8-9e0e92ec87fd.png)

**Comment by khakhulin** [comment]
Thanks, accidently removed from infer.py! Check in the example notebook.  I also add them in rome.py 
BTW, without aligning model also can be trained and used.
