### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by osushilover** [SamsungLabs/rome#4]
**There may be some elementary problems with this ipynb.
I run this cell on Colab Pro.**

`import os, sys
import importlib, warnings
import argparse
from glob import glob

from torchvision import transforms
from tqdm import tqdm
from PIL import Image

import cv2
import numpy as np
import torch
import matplotlib.pyplot as plt

os.chdir('..')

from src.utils import args as args_utils
from src.utils.processing import process_black_shape, tensor2image
from src.utils.visuals import mask_errosion

warnings.filterwarnings("ignore")

%load_ext autoreload
%autoreload 2`

And then, Here is the output said🧐
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-4420d587bbcb>](https://localhost:8080/#) in <module>()
     15 os.chdir('..')
     16 
---> 17 from src.utils import args as args_utils
     18 from src.utils.processing import process_black_shape, tensor2image
     19 from src.utils.visuals import mask_errosion

ModuleNotFoundError: No module named 'src'

**Comment by khakhulin** [comment]
if you are on colab, then probably your working directory is not correct (by default), please change it or add the correct path for import.

**Comment by khakhulin** [comment]
```
!  git clone https://github.com/SamsungLabs/rome.git
os.chdir('rome')
```
It will solve your problem
And be sure to remove os.chdir('..')
