### ISSUE TITLE
error

### ISSUE THREAD

**Issue by flynnamy** [SamsungLabs/rome#7]
Hi, I try to use jenya_driver to drive lincoln like notebooks doing, but meet error like following picture.  But I can work well by executing infer.py. Any suggestions? @khakhulin 
![image](https://user-images.githubusercontent.com/20398890/181750451-325388cc-146e-420e-b313-c10d2ab669ff.png)

**Comment by flynnamy** [comment]
If I set distill as True, it has error. Otherwise it is ok. Please check that. @khakhulin

**Comment by khakhulin** [comment]
I'm just check it locally on macbook everything works fine with this flag:
` python3 infer.py --deca DECA --rome data  --use_distill True`

Are you sure, that you are specifying correct checkpoint?
